### ISSUE TITLE
Event Listener

### ISSUE THREAD

**Issue by Mendes11** [and3rson/django-nameko#15]
Hi, thanks for the wrapper for django and for the update to django 2+

Is there any event_listener option for this wrapper? I couldn't find it in the README.

**Comment by 0xGosu** [comment]
@Mendes11 can you describe more about this use case?

**Comment by Mendes11** [comment]
I was thinking about enabling Django to dispatch events, but then I found out that nameko has it's standalone version that could do that.... Maybe django-nameko could have it so I wouldn't need to configure both django-nameko and nameko.standalone to dispatch events.

**Comment by 0xGosu** [comment]
Actually, I already have a block of code implementing this feature lying in my private repos. I can wrap it up along with some unit tests in next release `0.6.0` but right now don't have the time yet

**Comment by sivabudh** [comment]
If it means I can dispatch events right from within Django, it would be great.

**Comment by 0xGosu** [comment]
@sivabudh @Mendes11 This features has been implemented in version 0.7.0 Please check this PR: https://github.com/and3rson/django-nameko/pull/19

**Comment by sivabudh** [comment]
This looks interesting. I will try it when gotten a chance. Thanks!

**Comment by 0xGosu** [comment]
Close issue now since it is implemented
