### ISSUE TITLE
Requirements missing Django 2.0+

### ISSUE THREAD

**Issue by Mendes11** [and3rson/django-nameko#16]
Just installed django-nameko and it uninstalled my django 2.2 and installed 1.11.

I guess it's a requirements missing adjustment.

**Comment by 0xGosu** [comment]
thanks for notifying, indeed it missing adjustment in the setup.py requirement. Will update it now and push the fix asap

**Comment by 0xGosu** [comment]
@Mendes11 it is fixed in version `0.5.6`

**Comment by Mendes11** [comment]
@tranvietanh1991 Nice! Closing this issue :)
