### ISSUE TITLE
python3 compatiblity.

### ISSUE THREAD

**Issue by thj8** [and3rson/django-nameko#26]
```
                            for key in self._rpc._worker_ctx.data.keys():
                                del self._rpc._worker_ctx.data[key]
```
cloud not run in python3

**Comment by 0xGosu** [comment]
@thj8 can you please give exact version of python3 that you are having compatibility issue ?

**Comment by thj8** [comment]
> @thj8 can you please give exact version of python3 that you are having compatibility issue ?

@tranvietanh1991 3.7.3 thanks.

**Comment by 0xGosu** [comment]
@thj8 i've fixed it in this PR: https://github.com/and3rson/django-nameko/pull/27
