### ISSUE TITLE
When will be compatibility with django 2.1 and python3?

### ISSUE THREAD

**Issue by ikasymov** [and3rson/django-nameko#7]

**Comment by 0xGosu** [comment]
By the end of this year. I will make it compatible with django 2.x and python3.x. Versioning will jump to 1.x and leave 0.x.x to support django 1.11 and python 2.7

**Comment by ornoone** [comment]
@and3rson I'm working on a fork to support python 2.7, 3.5, 3.6, 3.7 + django 1.11, 2.0, 2.1, 2.2 + nameko 2.11, 2.12 

this fork is compose of :
- more unittesting, and a integration test with a running service + rabbitmq
- add tox to test on all versions
- add coverage to get 100 of code coverage
- integration with tarvis-ci parallel run for all python versions
- add flake8 and isort

i will make a PR soon so you can check it and maybe merge it if you're interested

**Comment by ornoone** [comment]
A just created the PR : https://github.com/and3rson/django-nameko/pull/12

**Comment by 0xGosu** [comment]
@ikasymov Support for Django 2.x and python 3.x has been provided in version `0.5.6`
